name: Deploy to Github
// need to adjust everything below to adjust for react native development
on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v4
     - name: Install modules
       run: npm install
     - name: Build dist
       run: npm run build

     - name: Deploy
     - id: deployment
